2023-05-07 03:24:02,535 ERROR: Exception on /auth/login [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\RealtyRadar\app\auth\routes.py", line 30, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Home\Flask\RealtyRadar\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Home\Flask\RealtyRadar\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Home\Flask\RealtyRadar\app\templates\base.html", line 13, in block 'navbar'
    <a class="blog-nav-item" href="{{ url_for('home.index') }}" }}>Аренда</a>
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home.index'. Did you mean 'house.index' instead?
2023-05-07 03:26:17,706 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
2023-05-08 23:05:56,008 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
2023-05-08 23:08:33,515 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
2023-05-08 23:12:28,949 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
2023-05-08 23:15:39,321 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
2023-05-08 23:23:28,557 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
2023-05-08 23:31:17,177 INFO: RealtyRadar startup [in C:\Users\Home\Flask\RealtyRadar\app\__init__.py:70]
