2023-04-29 19:03:28,733 ERROR: Exception on /reset_password_request [GET] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\routes.py", line 154, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password_request.html
2023-04-29 19:06:20,034 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:45]
2023-04-29 19:06:50,311 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Home\Flask\rr\app\email.py", line 12, in send_password_reset_email
    token = user.ger_reset_password_token()
AttributeError: 'User' object has no attribute 'ger_reset_password_token'
2023-04-29 19:07:56,705 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:45]
2023-04-29 19:08:21,906 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Home\Flask\rr\app\email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Home\Flask\rr\app\models.py", line 64, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2023-04-29 19:13:29,945 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:45]
2023-04-29 19:13:49,530 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Home\Flask\rr\app\email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Home\Flask\rr\app\models.py", line 64, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2023-04-29 19:14:10,933 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:45]
2023-04-29 19:14:29,382 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Home\Flask\rr\app\email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Home\Flask\rr\app\models.py", line 64, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2023-04-29 19:17:42,476 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:45]
2023-04-29 19:17:56,429 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Home\Flask\rr\app\routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Home\Flask\rr\app\email.py", line 16, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Home\Flask\rr\env\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2023-04-29 22:48:46,961 INFO: RealtyRadar startup [in C:\Users\Home\Flask\rr\app\__init__.py:45]
